name: Decapitation
version: '${project.version}'
author: Eviltechie
website: http://joe.to
main: to.joe.decapitation.Decapitation
softdepend: [Vault]
commands:
  setname:
    description: Sets the name of a skull
    permission: decapitation.setname
    permission-message: You may not set head names
    usage: /<command> [playername]
  clearname:
    description: Clears the name of a skull
    permission: decapitation.clearname
    permission-message: You may not clear head names
    usage: /<command>
  spawnhead:
    description: Spawns a player head with the given name
    permission: decapitation.spawnhead
    permission-message: You may not spawn heads
    usage: /<command> [playername] <quantity> <player>
  bounty:
    description: Place, claim, and search bounties bounties
    usage: /<command>
permissions:
  decapitation.setname:
    description: Set the name of skulls
  decapitation.clearname:
    description: Clear the name of skulls
  decapitation.spawnhead:
    description: Spawn heads with a given name
    children:
      decapitation.setname: true
  decapitation.dropheads:
    description: Ability to drop heads on death
    default: true
  decapitation.collectheads:
    description: Ability to collect heads when killing another player
    default: true
  decapitation.info:
    description: Get the name of a head
  decapitation.bounty:
    description: Place, claim, and search bounties bounties
    children:
      decapitation.bounty.search: true
      decapitation.bounty.list: true
      decapitation.bounty.place: true
      decapitation.bounty.claim: true
      decapitation.bounty.remove: true
      decapitation.bounty.listown: true
  decapitation.bounty.search:
    description: Search bounties
  decapitation.bounty.list:
    description: List bounties
  decapitation.bounty.place:
    description: Place bounties
  decapitation.bounty.claim:
    description: Claim (turn in) bounties
  decapitation.bounty.remove:
    description: Remove own bounties
  decapitation.bounty.listown:
    description: List own bounties
  decapitation.bounty.viewissuer:
    description: View who placed bounties when listing